config/routes.rb
Rails.application.routes.draw do
  root 'sessions#home'
  get '/login' => 'sessions#new'
  get '/external' => 'sessions#external'
  post '/login' =>  'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users
  resources :transportations
  resources :groups
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :transportations_groups
  has_many :transportations, through: :transportations_groups, dependent: :destroy

  has_one_attached :icon
  validates_presence_of :author_id, :icon
  validates :name, presence: true, length: { maximum: 40 }
  validates :icon, content_type: { in: %w[image/jpeg image/gif image/png],
                                   message: 'must be a valid image format' },
                   size: { less_than: 2.megabytes,
                           message: 'should be less than 2MB' }
  scope :order_group, -> { order('name') }
  scope :asc, -> { order('name ASC') }
end

app/models/transportation.rb
class Transportation < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :transportations_groups
  has_many :groups, through: :transportations_groups, dependent: :destroy
  validates_presence_of :distance
  validates :name, presence: true, length: { maximum: 40 }
  scope :transportation_list, -> { order(created_at: :desc) }
  scope :desc, -> { includes(:author).order('created_at DESC') }
end

app/models/transportations_group.rb
class TransportationsGroup < ApplicationRecord
  belongs_to :transportation
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  has_many :transportations, foreign_key: :author_id, dependent: :destroy
  has_many :groups, foreign_key: :author_id
  has_one_attached :picture
  validates_presence_of :first_name, :last_name, :username, :email
  validates_length_of :username, within: 6..12
  validates_uniqueness_of :username, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def index
    @groups = Group.all.order_group
    @groups = current_user.groups.asc unless current_user.groups.size.zero?
  end

  def create
    @user = current_user
    @group = @user.groups.build(group_params)
    @group.icon.attach(params[:group][:icon])
    if @group.save
      flash[:notice] = 'Group added successfully'
      redirect_to groups_path(@group)
    else
      flash.now[:notice] = 'Something is wrong, group not created'
      render 'new'
    end
  end

  def show
    @group = Group.find(params[:id])
    @groups = Group.all
    @transportations = @group.transportations unless current_user.transportations.size.zero?
    @group_sum = @transportations.sum(:distance)
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      flash[:notice] = 'Record updated successfuly'
      redirect_to groups_path
    else
      render('edit')
    end
  end

  def delete
    @group = Group.find(params[:id])
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:notice] = 'Record removed successfuly'
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:icon, :name, :author_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @page_title = 'User Login'
  end

  def index
    @page_title = 'Home'
  end

  def external
    @external_transportations = current_user.transportations
    return if @external_transportations.size.zero?

    @external_transportations = current_user.transportations.desc.reject { |t| t.groups.exists? }
    @external_sum = 0
    @external_transportations.each do |t|
      @external_sum += t.distance
    end
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user
      flash[:notice] = 'You have logged in successfully'
      session[:user_id] = @user.id
      session[:username] = @user.username
      redirect_to user_path(@user)
    else
      flash.now[:notice] = 'Something went wrong'
      render 'new'
    end
  end

  def destroy
    flash[:notice] = 'You have logged out successfully'
    session.delete(:user_id)
    session.delete(:username)
    @current_user = nil
    redirect_to('/')
  end
end

app/controllers/transportations_controller.rb
class TransportationsController < ApplicationController
  def new
    @page_title = 'Add New Transportation'
    @transportation = Transportation.new
    @groups = current_user.groups
  end

  def index
    @page_title = 'List Transportation'
    @transportations = current_user.transportations
    return if @transportations.size.zero?

    @transportations = current_user.transportations.desc.select { |t| t.groups.exists? }
    @sum = 0
    @transportations.each do |t|
      @sum += t.distance
    end
  end

  def create
    @transportation = current_user.transportations.build(transportation_params)
    @group = Group.find_by(id: group_params[:group_id])
    @transportation.groups << @group unless @group.nil?

    if @transportation.save
      flash[:notice] = 'Transportation created successfully!'
      redirect_to transportations_path
    else
      flash.now[:notice] = 'Something went wrong'
      render 'new'
    end
  end

  def show; end

  def destroy
    @transportation = Transportation.find(params[:id])
    @transportation.destroy
    flash[:notice] = 'Record removed successfuly'
    redirect_to transportations_path
  end

  def edit
    @transportation = Transportation.find(params[:id])
  end

  def update
    @transportation = Transportation.find(params[:id])
    if @transportation.update_attributes(transportation_params)
      flash[:notice] = 'Record updated successfuly'
      redirect_to transportations_path
    else
      flash.now[:notice] = 'Something went wrong'
      render 'edit'
    end
  end

  def delete
    @transportation = Transportation.find(params[:id])
  end

  private

  def transportation_params
    params.require(:transportation).permit(:name, :distance, :author_id)
  end

  def group_params
    params.require(:transportation).permit(:group_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show
    @user = User.find(params[:id])
  end

  def new
    @page_title = 'User Sign Up'
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.picture.attach(params[:user][:picture])
    if @user.save
      session[:author_id] = @user.id
      flash[:notice] = 'User created successfuly. Please, login'
      redirect_to '/'
    else
      flash.now[:notice] = 'Something went wrong'
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = 'User updated successfuly'
      redirect_to user_path(@user)
    else
      flash.now[:notice] = 'Something went wrong'
      render 'new'
    end
  end

  def delete; end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :picture, :email, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def whole_title(page_title = '')
    default_title = 'Group Our Transportation App'
    if page_title == ''
      default_title
    else
      page_title + '|' + default_title
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user?
    !session[:username].nil?
  end

  def current_user
    return unless (user_id = session[:id])

    @current_user ||= User.find(user_id)
  end
end

app/helpers/transportations_helper.rb
module TransportationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Groups#destroy</h1>
<p>Find me in app/views/groups/destroy.html.erb</p>

app/views/groups/edit.html.erb
<div class='sign-up-header'>
  <div class='trans-head-one'>
    <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-three-dots" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
    </svg>
    <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-battery-half" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M12 5H2a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1zM2 4a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2H2z"/>
      <path d="M2 6h5v4H2V6zm12.5 3.5a1.5 1.5 0 0 0 0-3v3z"/>
    </svg>
  </div>
  <div class='trans-head-two'>
  <%= link_to user_path(current_user) do %>
  <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-left" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
  </svg>
  <% end %>
     <h4 class='trans-list-title'>Edit Group</h4>
     <h4>NEXT</h4>
  </div>
</div>
<div class='container-fluid new-trans-form'>
<%= form_with model: @group, local: true, html: { multipart: true } do |f| %>
  <span class="flash"><%= flash.notice %></span>
    <div class='new-group-form'>
      <span class='span-g'><%= f.file_field :icon, accept: 'image/jpeg,image/gif,image/png' %></span>
      <h4>Upload Group Icon</h4>
    </div>
    <div id='new-group-form'>
      <%= f.text_field :name, placeholder: 'Enter Group Name', class: 'form-control group-text-input' %>
    </div>
    <div class="">
      <%= f.submit 'Update Group', class: 'new-transport btn btn-primary' %>
    </div>
<% end %>
</div>

app/views/groups/index.html.erb
<div class='trans-header'>
  <div class='trans-head-one'>
    <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-three-dots" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
    </svg>
    <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-battery-half" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M12 5H2a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1zM2 4a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2H2z"/>
      <path d="M2 6h5v4H2V6zm12.5 3.5a1.5 1.5 0 0 0 0-3v3z"/>
    </svg>
  </div>
  <div class='trans-head-two'>
    <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-list" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
    </svg>
     <h4 class='trans-list-title'>Transportation Groups</h4>
     <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
       <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
       <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
     </svg>
  </div>
  <div class='trans-head-three'>
  <%= link_to current_user.username, user_path(current_user), class: 'to-profile' %>
  </div>
</div>
<div class='set-group-index'>
<span class="flash"><%= flash.notice %></span>
<table class="table table-responsive row-box">
  <thead>
    <tr class='group-heading'>
      <th>Icon</th>
      <th>Group Name</th>
      <th>Creation Date</th>
    </tr>
  </thead>
  <tbody>
    <tr><% @groups.includes([:icon_attachment]).each do |t| %></tr>
      <td><%= image_tag t.icon.variant(resize_to_limit: [40, 40]) if t.icon.attached? %></td>
      <td><%= link_to t.name, group_path(t.id), class: 'group-name' %></td>
      <td><span class = 'format_date'><%= t.created_at.to_formatted_s(:long) %></span></td>
      <td><%= link_to 'Edit', edit_group_path(t.id) %> |
      <%= link_to 'Delete', group_path(t), method: :delete, data: { confirm: 'Are you really sure?' } %>
    <% end %> 
  </tbody>
</table>
</div>
<div class='table-green'>
<h3><%= link_to 'Create New', new_group_path, class: 'table-h3' %></h3>
</div>

app/views/groups/new.html.erb
<div class='sign-up-header'>
  <div class='trans-head-one'>
    <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-three-dots" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
    </svg>
    <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-battery-half" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M12 5H2a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1zM2 4a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2H2z"/>
      <path d="M2 6h5v4H2V6zm12.5 3.5a1.5 1.5 0 0 0 0-3v3z"/>
    </svg>
  </div>
  <div class='trans-head-two'>
  <%= link_to user_path(current_user) do %>
  <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-left" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
  </svg>
  <% end %>
     <h4 class='trans-list-title'>New Group</h4>
     <h4>NEXT</h4>
  </div>
</div>
<div class='container-fluid new-trans-form'>
<%= form_with model: @group, local: true, html: { multipart: true } do |f| %>
  <span class="flash"><%= flash.notice %></span>
    <div class='new-group-form'>
      <%= f.file_field :icon, accept: 'image/jpeg,image/gif,image/png' %>
      <h4>Upload Group Icon</h4>
    </div>
    <div id='new-group-form'>
      <%= f.text_field :name, placeholder: 'Enter Group Name', class: 'form-control group-text-input' %>
    </div>
    <div class="">
      <%= f.submit 'Create Group', class: 'new-transport btn btn-primary' %>
    </div>
<% end %>
</div>

app/views/groups/show.html.erb
<div class='sign-up-header'>
  <div class='trans-head-one'>
    <svg width="3.5rem" height="3.5rem" viewBox="0 0 16 16" class="bi bi-three-dots" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
    </svg>
    <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-battery-half" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M12 5H2a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1zM2 4a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2H2z"/>
      <path d="M2 6h5v4H2V6zm12.5 3.5a1.5 1.5 0 0 0 0-3v3z"/>
    </svg>
  </div>
  <div class='trans-head-two'>
  <%= link_to groups_path(@group) do %>
  <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-left" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
  </svg>
  <% end %>
  <h4 class='group-head-name'><%= @group.name %></h4>
     <h4>NEXT</h4>
  </div>
</div>
<div class='sum_in_km'>
   <div class='sum-box'>
     <h2>Total Distance</h2>
     <h2><%= @group_sum.to_s + 'KM'%></h2>
   </div>
</div>
<div>
<div class='list-group-members'>
<span class="flash"><%= flash.notice %></span>
<table class="table table-responsive row-box">
    <thead>
    <tr>
      <th>Icon</th>
      <th>Transportation Means</th>
      <th>Distance (KM)</th>
      <th>Creator</th>
    </tr>
  </thead>
  <tbody>
    <tr><% @transportations.each do |t| %></tr>
      <td><%= image_tag t.groups.first.icon.variant(resize_to_limit: [60, 60]) if t.groups.first.icon.attached? %></td>
      <td><%= t.name %><br/><span class = 'format_date'><%= t.created_at.to_formatted_s(:long) %></span></td>
      <td><%= t.distance.to_s + 'KM' %></td>
      <td class='creator-name'><%= t.author.username %></td>
    <% end %> 
 </tbody>
</table>
</div>
<div class='table-green'>
   <h3><%= link_to 'Add Transportation', new_transportation_path, class: 'table-h3' %></h3>
</div>
</div>

app/views/layouts/_display_profile_picture.html.erb
<% if @user.picture.attached? %>
    <div id='profile-pic' >
      <%= image_tag @user.picture.variant(resize_to_limit: [100, 100]), class: 'img-circle' %>
    </div>
<% else %>
      <%= link_to 'Add Picture', edit_user_path(@user), class: 'user-picture' %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
  <a href= '#' class='footer-text' >Group our transport app </a>
  by <a href= '#' class='footer-text'>Zubenna</a>
  </small>
  <nav>
  <ul class='footer-nav'>
    <li><%= link_to 'About', '#', class: 'footer-text' %></li>
    <li><%= link_to 'Contact', '#', class: 'footer-text' %></li>
    <li><%= link_to 'News', '#', class: 'footer-text' %></li>
  </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbarfixed-top">
<nav>
<ul class="home-list">
  <% if !current_user? %>
  <li><%= link_to "Group Our Transportation App", '#', id: "logo" %></li>
  <li><%= link_to 'Home', '/', class: 'home-link' %></li>
  <% end %>
</ul>
</nav>
</header>
        

app/views/layouts/_listing.html.erb
  <div class='sum_in_km' >
     <div class='sum-box'>
       <h2>Total Distance</h2>
       <h3 class='total-sum'><%= @sum.to_s + 'KM' %></h3>
     </div>
  </div>
<div class='table-container'>  
 <div id='list-transportation'>
 <span class="flash"><%= flash.notice %></span>  
 <table class="table table-responsive row-box">
    <thead>
    <tr>
      <th>Icon</th>
      <th>Transportation Description</th>
      <th>Distance (KM)</th>
    </tr>
    </thead>
  <tbody>
    <tr><% @transportations.each do |t| %></tr>
      <td><%= image_tag t.groups.first.icon.variant(resize_to_limit: [35, 35]) if t.groups.first.icon.attached? %></td>
      <td><%= t.name %><br/><span class = 'format_date'><%= t.created_at.to_formatted_s(:long) %></span></td>
      <td class='bold-distance'><%= t.distance.to_s + 'KM' %></td>
      <td><%= link_to 'Edit', edit_transportation_path(t.id) %> |
      <%= link_to 'Delete', transportation_path(t), method: :delete, data: { confirm: 'Are you really sure?' } %>
      </td>
    <% end %> 
 </tbody>
</table>
</div>
<div class='table-green'>
<h3><%= link_to 'Add Transportation', new_transportation_path, class: 'table-h3' %></h3>
</div>
</div>

app/views/layouts/_user-options.html.erb
<ul class='user-option-ul'>
<li><%= link_to 'All my transportations', transportations_path, id: 'link-one' %> </li>
<li><%= link_to 'All my ungrouped transportations', users_path %> </li>
<li><%= link_to 'Different means of transportations', groups_path %> </li>
</ul>

app/views/transportations/show.html.erb
<h1>Transportations#show</h1>
<p>Find me in app/views/transportations/show.html.erb</p>

app/views/users/show.html.erb
<div class='profile-box'>
    <section class='user-pic-box'>
    <%= render 'layouts/display_profile_picture' %>
    <h4>
    <%= @user.first_name %>
    <%= @user.last_name %>
    </h4>
    <span class="flash"><%= flash.notice %></span>
    </section>
    <section class='profile-body'>
    <div class='option-box'>
      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-list shape-icon circle-me" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
        <path fill-rule="evenodd" d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5z"/>
      </svg>
      <div class='option-link'>
        <%= link_to '  All my logged in transportations', transportations_path, class: 'user-option-li' %>
      </div>
    </div>
    <div class='option-box'>
      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-geo-alt shape-icon circle-me" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M12.166 8.94C12.696 7.867 13 6.862 13 6A5 5 0 0 0 3 6c0 .862.305 1.867.834 2.94.524 1.062 1.234 2.12 1.96 3.07A31.481 31.481 0 0 0 8 14.58l.208-.22a31.493 31.493 0 0 0 1.998-2.35c.726-.95 1.436-2.008 1.96-3.07zM8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10z"/>
        <path fill-rule="evenodd" d="M8 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
      </svg>
    <div class='option-link'>
      <%= link_to 'All my ungrouped transportations', external_path, class: 'user-option-li center-link' %>
    </div>
    </div>
    <div class='option-box'>
      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-collection-fill shape-icon circle-me" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path d="M0 13a1.5 1.5 0 0 0 1.5 1.5h13A1.5 1.5 0 0 0 16 13V6a1.5 1.5 0 0 0-1.5-1.5h-13A1.5 1.5 0 0 0 0 6v7z"/>
        <path fill-rule="evenodd" d="M2 3a.5.5 0 0 0 .5.5h11a.5.5 0 0 0 0-1h-11A.5.5 0 0 0 2 3zm2-2a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 0-1h-7A.5.5 0 0 0 4 1z"/>
      </svg>
    <div class='option-link'>
      <%= link_to 'Different means of transportations', groups_path, class: 'user-option-li' %>
    </div>
    </div>
    <%= link_to 'Log Out', '/logout', class: 'btn btn-lg log-out', method: :delete %>
    </section>
</div>